"""Shared sampling policies and contract errors."""

from __future__ import annotations

from typing import TYPE_CHECKING, TypedDict

if TYPE_CHECKING:
    import numpy as np
    from numpy.typing import NDArray
    from torch import Tensor


class TopologyArrayState(TypedDict):
    """The topology-only decoder deliberately omits chemical state fields."""

    parents: NDArray[np.int64]
    closure_left: NDArray[np.int64]
    closure_right: NDArray[np.int64]


class TerminalArrayState(TopologyArrayState):
    """One complete decoded graph before batching."""

    nodes: NDArray[np.int64]
    parent_bonds: NDArray[np.int64]
    closure_bonds: NDArray[np.int64]


class TerminalTensorState(TypedDict):
    """The six complete graph tensors returned by terminal decoding."""

    nodes: Tensor
    parents: Tensor
    parent_bonds: Tensor
    closure_left: Tensor
    closure_right: Tensor
    closure_bonds: Tensor


CHECKPOINT_SCHEMA = "forge.synthesis_program_sparse_flow_checkpoint.v1"

JOINT_SAMPLING_FACTORIZATION = "joint"

LEARNED_TOPOLOGY_THEN_CHEMISTRY_FACTORIZATION = "learned_topology_then_chemistry"

SUPPORTED_SAMPLING_FACTORIZATIONS = frozenset(
    {
        JOINT_SAMPLING_FACTORIZATION,
        LEARNED_TOPOLOGY_THEN_CHEMISTRY_FACTORIZATION,
    }
)

TERMINAL_DECODE_POLICIES = (
    "unconstrained_argmax",
    "strict_valence_topology_argmax",
)

LOCAL_CHEMISTRY_TERMINAL_DECODE_POLICY = "strict_local_chemistry_argmax"

PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICY = "strict_program_topology_argmax"

COUPLED_UGI_TOPOLOGY_TERMINAL_DECODE_POLICY = "strict_ugi_program_coupled_conditional"

CORE_SATURATION_TERMINAL_DECODE_POLICY = "strict_reaction_core_saturation_argmax"

ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY = (
    "strict_role_local_closure_chemistry_core_saturation_argmax"
)

UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY = (
    "strict_ugi_topology_role_local_chemistry_core_saturation"
)

UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY = (
    "strict_ugi_topology_role_local_chemistry_core_saturation_stochastic"
)

UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY = (
    "strict_ugi_ester_topology_role_local_chemistry_core_saturation"
)

UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY = (
    "strict_ugi_ester_topology_role_local_chemistry_core_saturation_stochastic"
)

UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY = (
    "strict_ugi_ester_topology_role_local_chemistry_core_saturation_mog_guided"
)

UGI_TOPOLOGY_COUPLED_TERMINAL_DECODE_POLICIES = frozenset(
    {
        COUPLED_UGI_TOPOLOGY_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

LOCAL_CHEMISTRY_TERMINAL_DECODE_POLICIES = frozenset(
    {
        LOCAL_CHEMISTRY_TERMINAL_DECODE_POLICY,
        ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICIES = frozenset(
    {
        PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICY,
        COUPLED_UGI_TOPOLOGY_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

PROGRAM_CYCLE_TERMINAL_DECODE_POLICIES = frozenset(
    {
        *PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICIES,
        ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY,
    }
)

COMPONENT_CONFINED_TERMINAL_DECODE_POLICIES = frozenset(
    {
        *PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICIES,
    }
)

CORE_SATURATION_TERMINAL_DECODE_POLICIES = frozenset(
    {
        CORE_SATURATION_TERMINAL_DECODE_POLICY,
        ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

SUPPORTED_TERMINAL_DECODE_POLICIES = (
    *TERMINAL_DECODE_POLICIES,
    LOCAL_CHEMISTRY_TERMINAL_DECODE_POLICY,
    PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICY,
    COUPLED_UGI_TOPOLOGY_TERMINAL_DECODE_POLICY,
    CORE_SATURATION_TERMINAL_DECODE_POLICY,
    ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY,
    UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
    UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
    UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
    UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
    UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
)

STOCHASTIC_TERMINAL_DECODE_POLICIES = frozenset(
    {
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

UGI_ESTER_TERMINAL_DECODE_POLICIES = frozenset(
    {
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)

STRICT_TERMINAL_DECODE_POLICIES = frozenset(
    {
        "strict_valence_topology_argmax",
        LOCAL_CHEMISTRY_TERMINAL_DECODE_POLICY,
        PROGRAM_TOPOLOGY_TERMINAL_DECODE_POLICY,
        COUPLED_UGI_TOPOLOGY_TERMINAL_DECODE_POLICY,
        CORE_SATURATION_TERMINAL_DECODE_POLICY,
        ROLE_LOCAL_SUPPORTED_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_STOCHASTIC_TERMINAL_DECODE_POLICY,
        UGI_ESTER_TOPOLOGY_ROLE_LOCAL_MOG_TERMINAL_DECODE_POLICY,
    }
)


class SynthesisProgramSamplingError(ValueError):
    """A shared synthesis-program sampling request violates its fixed-state contract."""
